CREATE TABLE TASKS
(
    ScheduleID VARCHAR(100) PRIMARY KEY COMMENT 'ID',
    Content VARCHAR(1000) NOT NULL COMMENT '내용',
    Name VARCHAR(100) NOT NULL COMMENT '관리자명',
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '작성일',
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일',
    Password VARCHAR(100) NOT NULL COMMENT '비밀번호'
);