CREATE TABLE TASKS
(
    ID VARCHAR(100) PRIMARY KEY COMMENT 'ID',
    CONTENT VARCHAR(1000) NOT NULL COMMENT '내용',
    NAME VARCHAR(100) NOT NULL COMMENT '관리자명',
    PASSWORD VARCHAR(100) NOT NULL COMMENT '비밀번호',
    DATE DATETIME NOT NULL COMMENT '작성/수정일'
);